### ISSUE TITLE
nova.touch.bindClick issue on Android version

### ISSUE THREAD

**Issue by rascal-mobile56** [nova-framework/app#28]
Hello, Nova Team
I already build iOS and Android app using Nova Framework.
I implemented nova.touch.bindClick on this project .
iOS version is working well  but android version is not working well.
When I tap button 100 times , it is working.

 nova.touch.bindClick('#btnCardReadings', function () {               
                app.gotoPage("pages/cards.html");
                app.game.newGame();
                return true;
            });

can you help my issue ? and What is my issue here.
Important!, iOS version is working well, there is no issue

**Comment by dcblogdev** [comment]
Nova framework runs on a PHP server there is not IOS or Android support for it.

Are you confusing a mobile framework with Nova?

**Comment by rascal-mobile56** [comment]
yes

**Comment by rascal-mobile56** [comment]
I mean I built Cordova mobile application using Nova framework
Btw, it was working on iOS version, but it is not working on Android version

**Comment by dcblogdev** [comment]
In that case ask on the Cordova site it's outside the scope of Nova and a third party issue.
