### ISSUE TITLE
Composer error

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/app#3]
I amg getting

```
  [RuntimeException]
  Failed to clone https://github.com/nova-framework/system, git was not found, check that it is installed and in your
   PATH env.
  'git' is not recognized as an internal or external command,
  operable program or batch file.
```

I am running composer from the https://github.com/nova-framework/app I downloaded.
Shouldn't this install with or without git?
The composer line I used

```
composer create-project nova-framework/app novtmp -s dev
```

I do have github installed, but this shouldn't have anything to do with it.

**Comment by ghost** [comment]
I think it is something on your end. I ran:

```
composer create-project nova-framework/app novtmp -s dev
```

and it worked fine.

Have you correctly set your PATH to point at your git installation?

**Comment by jimgwhit** [comment]
@Kingorgg my composer is global, not sure about git, could you give example, but shouldn't it install if someone didnot have github desktop?  
Also can yo give the new folder structure for nova 4, composer pulled in system after I donloaded it, but does those files go under system or main project folder?

**Comment by jimgwhit** [comment]
@Kingorgg see previous, My email is kpsklab@yahoo.com if you need to send me example folder structure.

**Comment by jimgwhit** [comment]
I installed git, trying again, but really I don't see why git is required.

**Comment by jimgwhit** [comment]
After installing git it worked, I have never had to have git before for a composer install, why now?
